import EXT.DOMAIN.cpe.vpr.pom.PatientEvent
import EXT.DOMAIN.cpe.vpr.Patient
import EXT.DOMAIN.cpe.vpr.Medication
import EXT.DOMAIN.cpe.vpr.Allergy
import EXT.DOMAIN.cpe.vpr.frameeng.FrameAction.AlertAction
import EXT.DOMAIN.cpe.vpr.pom.IGenericPatientObjectDAO

global IGenericPatientObjectDAO DAO;

rule "Calculate Score when requested"
  when
  	$e : CallEvent(entryPoint == 'FRAMINGHAM')
    $p : Patient() from $e.source
  then
  	$score : 0
end


