import org.osehra.cpe.vpr.pom.PatientEvent
import org.osehra.cpe.vpr.Patient
import org.osehra.cpe.vpr.Medication
import org.osehra.cpe.vpr.Allergy
import org.osehra.cpe.vpr.frameeng.FrameAction.AlertAction
import org.osehra.cpe.vpr.pom.IGenericPatientObjectDAO

global IGenericPatientObjectDAO DAO;

rule "Hello World"
  when
      $e : PatientEvent(source.class == Patient.class)
      $p : Patient() from $e.source
  then
      insert(new AlertAction(null, 'droolsalerta', $p.getPid(), "drools alert", $p.getSsn()));
end

/* Example of rule chaining.... */
rule "alert triggered alert"
	when
		$a : AlertAction(title == "drools alert")
	then
		insert(new AlertAction(null, 'droolsalertb', $a.getPID(), drools.getRule().getName(), "this is to alert you of an alert"));
end

/*
rule "allergy/medication contraindication"
	when
		$e : PatientEvent(source.class == Medication.class, $pid : source.pid)
		$allergies : Allergy() from DAO.findAllByPID(Allergy.class, $pid, null)
	then
		
end
*/

